#ifndef CONSTANTS_H_INCLUDED
#define CONSTANTS_H_INCLUDED

using namespace std;

enum DIRECTION {UP=0, RIGHT=1, DOWN=2, LEFT=3};
enum COMMANDS {MOVE=0, ROTATE=1, LIGHT=2};

#endif // CONSTANTS_H_INCLUDED
